import os
import glob
from google import genai
from google.genai import types

# Load API key from .env file
def load_api_key():
    env_path = "/Users/vijayakumarjermansraj/Desktop/google_antigravity/yt_simple_tips/.env"
    if os.path.exists(env_path):
        with open(env_path, "r") as f:
            for line in f:
                if line.startswith("GEMINI_API_KEY="):
                    return line.strip().split("=", 1)[1]
    return os.getenv("GEMINI_API_KEY", "")

api_key = load_api_key()
if not api_key:
    print("Error: GEMINI_API_KEY not found.")
    exit(1)

client = genai.Client(api_key=api_key)

frames_dir = "/Users/vijayakumarjermansraj/.gemini/antigravity-ide/brain/abd58446-2477-4b00-adca-56798e8def07"
frame_paths = sorted(glob.glob(os.path.join(frames_dir, "frame_*.png")))

if not frame_paths:
    print("Error: No frames found to analyze.")
    exit(1)

print(f"Analyzing {len(frame_paths)} frames using Gemini Multimodal...")

prompt = """
You are an expert video quality assurance engineer. You are inspecting a widescreen (16:9, 1920x1080) landscape video that was automatically generated by a pipeline. This pipeline was originally designed for vertical Shorts (9:16) but has been modified/forced to render in widescreen.

Inspect the attached video frames closely and list ALL visual, rendering, layout, alignment, and composition issues.
Look specifically for:
1. Title banner: Is it positioned correctly? Is it cropped or only partially covering the screen? (Normally it should span the full width, but here it might be 1080px wide on a 1920px screen).
2. Subtitles: Are they readable? Are they centered? Are any text boxes cut off at the bottom, top, or sides?
3. English keyword pills: Are they positioned correctly? Are they cut off at the bottom of the screen?
4. Avatar (Talking Head / VJ): Is the avatar cropped, scaled correctly, or showing green background screen outline or other keying artifacts?
5. Content panels / Background: Are the images or B-roll cropped weirdly or showing empty canvas regions?
6. Retention badges (Fact Counter, Countdown Timer, Sound-On indicator, Watermark): Are they visible? Are any of them pushed off-screen or rendered in weird positions due to height differences (e.g. at y > 1080)?
7. Any other formatting, stretching, or resolution mismatch errors.

For each frame, provide a bulleted list of issues you see, referencing the time in the frame filename. Then provide a final summary of all critical issues and what is causing them in the codebase.
"""

contents = [prompt]
for path in frame_paths:
    filename = os.path.basename(path)
    print(f"Loading {filename}...")
    try:
        from PIL import Image
        img = Image.open(path)
        contents.append(img)
        contents.append(f"\n--- Frame: {filename} ---")
    except Exception as e:
        print(f"Error loading {path}: {e}")

print("Sending request to Gemini 2.5 Flash...")
try:
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=contents,
    )
    print("\n=== ANALYSIS RESULT ===")
    print(response.text)
    
    # Save the analysis result to a text file
    report_path = "/Users/vijayakumarjermansraj/.gemini/antigravity-ide/brain/abd58446-2477-4b00-adca-56798e8def07/video_analysis_report.txt"
    with open(report_path, "w") as f:
        f.write(response.text)
    print(f"\nSaved report to {report_path}")
    
except Exception as e:
    print(f"Gemini API Call failed: {e}")
